### ISSUE TITLE
How to support termination of subprocess via unix signal (eg sigint, sigkill)

### ISSUE THREAD

**Issue by jlgerber** [hniksic/rust-subprocess#48] opened 2020-08-26 20:13 UTC
Is there a canonical way of handling subprocess termination? I am doing something like this:

```
let exit_status = Exec::shell(cms).cwd(cwd.as_str()).join()?
```
When the program runs, typing CTRL-C terminates the parent process, but the subprocess continues on its merry way. 
I guess i can get the popen handle, put it in behind an ```Arc<Mutex>>``` and use the ctrlc library. Or use a process group maybe. Thoughts?

**Comment by hniksic** [comment] 2020-08-26 21:09
> When the program runs, typing CTRL-C terminates the parent process, but the subprocess continues on its merry way.

What OS are you observing this on? I cannot reproduce it on Linux (Ubuntu, `/bin/sh` is `dash`). For example, using this code:

```
fn main() {
    let x = Exec::shell("sleep 100").join().unwrap();
}
```

when I start the program and press <kbd>^C</kbd>, `sleep` is not listed among running processes.

**Comment by jlgerber** [comment] 2020-08-27 14:08
I am running this on centos7.
I am invoking a series of commands which are in turn invoking commands in their own subprocess (we have a wrapper system for executables that initializes a runtime environment and then shells out and invokes the actual executable) so the situation is a bit more complex.

I ended up using ctrl-c, and modifying the shell invocation a bit to allow sharing an ```Arc<Mutex<Popen>>``` which I use to call popen.terminate() from the ctrl-c handler in the event of an appropriate signal.

**Comment by hniksic** [comment] 2020-08-27 16:50
Do you have a minimal example that reproduces the issue? For example, does it occur when you try a simple `Exec::shell("sleep 100").join().unwrap()` as I did? I think `subprocess` shouldn't _cause_ ctrl-c to get lost.

> I ended up using ctrl-c, and modifying the shell invocation a bit to allow sharing an `Arc<Mutex<Popen>>` which I use to call popen.terminate() from the ctrl-c handler in the event of an appropriate signal.

It's a pity that you need to use a mutex to call `terminate()` which ends up just using a syscall which can't cause data races or anything like it.

Ideally not only `terminate()`, but all subprocess methods, would take `&self` and lock internally as appropriate, so the API user doesn't need to care about locking. But I think the API would need to change incompatibly because `stdin`, `stdout`, and `stderr` are currently fields, and they would have to be locked as well. It is not clear to me how useful thread safety would be in practice for most users, and `Mutex` is an okay workaround.

**Comment by hniksic** [comment] 2020-09-15 20:23
Closing as the issue appears not to be generally reproducible and the submitter has found a workaround.

Please reopen if you find a way to reproduce.

**Closed by hniksic** 2020-09-15 20:23 UTC
