### ISSUE TITLE
why is Capture not exposed

### ISSUE THREAD

**Issue by tshepang** [hniksic/rust-subprocess#15] opened 2018-08-23 09:59 UTC
I found myself wanting to use value given by Capture, and found that the struct is sort of private... it's not visible from outside the crate. Is it an oversight?

**Comment by hniksic** [comment] 2018-09-18 18:15
Can you specify which code you'd  like to write by using `Capture` directly? The value was designed to be an intermediate proxy for methods such as `stdout_str()`. If it's useful, though, it wouldn't hurt to export it.

**Comment by tshepang** [comment] 2018-09-18 19:29
Having a single type that has stdout, stderr, and ExitStatus is convenient. I wrote an API that offers the ease of using `Exec::shell` without having to call out to a shell, as well as some other niceties, like debug logging the commands executed. It returns Capture type (which I had to create, since one of the crate is private).

**Comment by hniksic** [comment] 2018-09-22 12:47
I've now taken another look at the code - `Capture` is kept semi-private (kind of like `impl` trait), partly because there are in fact _two_ different capture types: `Capture` returned by `Exec::capture`, and `CaptureOutput` returned by `Pipeline::capture`. The two should probably be merged if the type is to be publically exposed.

**Comment by tshepang** [comment] 2018-09-22 19:05
Just as a note, I am only interested in `Capture` as returned by `Exec::capture`

**Comment by hniksic** [comment] 2018-09-24 19:58
`Capture` (now `CaptureData`) is now part of the public API. The same type is returned from `Exec::capture` and `Pipeline::capture`, and in both cases it contains both the standard output and the standard error.

**Closed by hniksic** 2018-09-24 19:58 UTC

**Comment by tshepang** [comment] 2018-09-24 20:29
too excellent!
